spring:
  application.name: mikaelhg's Spring Boot MVC example
  config.name: springmvc-example

  main:
    web-environment: true
    show-banner: true
    log-startup-info: false

server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 0

---
spring.profiles: default

spring:
  datasource:
    driverClassName: org.h2.Driver
  database:
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---
spring.profiles: postgresql

spring:
  datasource:
    driverClassName: org.postgresql.Driver
  database:
    platform: postgresql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
spring.profiles: mysql

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
  database:
    platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
