spring:
  application.name: mikaelhg's Spring Boot MVC example
  config.name: springmvc-example

  main:
    web-environment: true
    show-banner: true
    log-startup-info: false

  jpa.show-sql: false

  thymeleaf.cache: true

server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 0

---
spring.profiles: default

spring.database.platform: h2
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.thymeleaf.cache: false

---
spring.profiles: postgresql

# TODO: NEEDS FIXING WHEN SPRING BOOT FIXES NON-EMBEDDED AUTODETECTION

spring:
  database:
    platform: postgresql
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
spring.profiles: mysql

# TODO: NEEDS FIXING WHEN SPRING BOOT FIXES NON-EMBEDDED AUTODETECTION

spring:
  database:
    platform: mysql
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
